[tools]
## Stack
node = { version = "lts", postinstall = "corepack enable" }
bun = "latest"

[settings]
# Enable extra features
experimental = true
# Consume Node.js version from .nvmrc, .tool-versions, etc.
idiomatic_version_file_enable_tools = ["node"]
