name: Smoke tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
      - run: pnpm install

      - name: Smoke tests
        run: ./scripts/test/smoke.sh
